DROP TABLE IF EXISTS PARTIE;
DROP TABLE IF EXISTS EQUIPE;

CREATE TABLE EQUIPE (
    idEqu INT PRIMARY KEY,
    symbole VARCHAR(50) UNIQUE NOT NULL,
    score INT DEFAULT 0
);

INSERT INTO EQUIPE (idEqu, symbole) VALUES
(0, ' '),
(1, 'J'),
(2, 'R');

CREATE TABLE PARTIE (
    idPart INT AUTO_INCREMENT PRIMARY KEY,
    datePart DATE NOT NULL,
    idEquGagn INT,
    FOREIGN KEY (idEquGagn) REFERENCES EQUIPE(idEqu)
);
