DROP TABLE IF EXISTS PARTIE;
DROP TABLE IF EXISTS JOUEUR;

CREATE TABLE JOUEUR (
    nomJoueur VARCHAR(32) PRIMARY KEY,
    score INT
);

CREATE TABLE PARTIE (
    idPart INT AUTO_INCREMENT PRIMARY KEY,
    datePart DATE NOT NULL,
    joueur1 VARCHAR(32),
    joueur2 VARCHAR(32),
    gagnant VARCHAR(32),
    FOREIGN KEY (joueur1) REFERENCES JOUEUR(nomJoueur),
    FOREIGN KEY (joueur2) REFERENCES JOUEUR(nomJoueur)
);
